import { INestApplication } from '@nestjs/common';
import { ConfigModule } from '@nestjs/config';
import { Test, TestingModule } from '@nestjs/testing';
import request from 'supertest';
import { App } from 'supertest/types';
import { ClerkAuthGuard } from '../../src/auth/guards/clerk-auth.guard';
import { DashboardModule } from '../../src/dashboard/dashboard.module';
import { PrismaModule } from '../../src/prisma/prisma.module';
import { PrismaService } from '../../src/prisma/prisma.service';
import type { User } from '../../src/generated/prisma/client';
import { createTestApp } from '../helpers/create-test-app';
import { MockClerkAuthGuard } from '../helpers/mock-clerk-auth.guard';
import { requireTestDatabase } from '../helpers/test-db';

requireTestDatabase();

// ─── Stable IDs — hex-only prefix e2ed0000 ────────────────────────────────────
const E2E_SP_MUT_BIZ_ID = 'e2ed0000-0000-4000-8000-000000000001';
const E2E_SP_MUT_OWNER_USER_ID = 'e2ed0000-0000-4000-8000-000000000002';
const E2E_SP_MUT_MGR_USER_ID = 'e2ed0000-0000-4000-8000-000000000003';
const E2E_SP_MUT_MBR_USER_ID = 'e2ed0000-0000-4000-8000-000000000004';
const E2E_SP_MUT_OUT_USER_ID = 'e2ed0000-0000-4000-8000-000000000005';
// Dedicated user/BU for the pre-seeded ServiceProvider (update/status tests)
const E2E_SP_MUT_SP_USER_ID = 'e2ed0000-0000-4000-8000-000000000006';
// SP seeded with only an inactive service (for activation-invariant tests)
const E2E_SP_MUT_INACT_SVC_SP_USER_ID = 'e2ed0000-0000-4000-8000-000000000007';
const E2E_SP_MUT_INACT_SVC_SP_ID = 'e2ed0000-0000-4000-8000-000000000020';
// Backup active provider also linked to E2E_SP_MUT_ACTIVE_SVC_ID, so the
// status-endpoint RBAC tests can freely toggle existingSpId without tripping
// the "last active provider of an active service" guard.
const E2E_SP_MUT_BACKUP_SP_USER_ID = 'e2ed0000-0000-4000-8000-000000000008';
// Dedicated single-active-provider/single-active-service pair used only by
// the orphan-protection tests, kept isolated from the rest of the suite.
const E2E_SP_MUT_ORPHAN_SP_USER_ID = 'e2ed0000-0000-4000-8000-000000000009';
const E2E_SP_MUT_ORPHAN_SP_ID = 'e2ed0000-0000-4000-8000-000000000021';
const E2E_SP_MUT_ORPHAN_SVC_ID = 'e2ed0000-0000-4000-8000-000000000012';
// Services
const E2E_SP_MUT_ACTIVE_SVC_ID = 'e2ed0000-0000-4000-8000-000000000010';
const E2E_SP_MUT_INACTIVE_SVC_ID = 'e2ed0000-0000-4000-8000-000000000011';
// Cross-tenant fixture
const E2E_SP_MUT_OTHER_BIZ_ID = 'e2ed0000-0000-4000-8000-000000000030';
const E2E_SP_MUT_OTHER_USER_ID = 'e2ed0000-0000-4000-8000-000000000031';
const E2E_SP_MUT_OTHER_SVC_ID = 'e2ed0000-0000-4000-8000-000000000032';

type ServiceProviderDto = {
  id: string;
  displayName: string;
  isActive: boolean;
  businessUserId: string;
  serviceIds: string[];
  createdAt: string;
  updatedAt: string;
};

// ─── Shared module-level setup ────────────────────────────────────────────────

let app: INestApplication<App>;
let prisma: PrismaService;
let ownerUser: User;
let managerUser: User;
let memberUser: User;
let outsiderUser: User;

// BusinessUser IDs captured at runtime (auto-generated by Prisma)
let ownerBUId: string;
let managerBUId: string;
let memberBUId: string; // used for validation tests that need a BU without a pre-existing SP
let spBUId: string; // dedicated BU for the pre-seeded ServiceProvider
let existingSpId: string; // pre-seeded SP used by update/status tests
let otherSpId: string; // cross-tenant SP

beforeAll(async () => {
  const module: TestingModule = await Test.createTestingModule({
    imports: [
      ConfigModule.forRoot({ ignoreEnvFile: true, isGlobal: true }),
      PrismaModule,
      DashboardModule,
    ],
  })
    .overrideGuard(ClerkAuthGuard)
    .useClass(MockClerkAuthGuard)
    .compile();

  app = await createTestApp(module);
  prisma = module.get(PrismaService);

  // ── Idempotent pre-cleanup ─────────────────────────────────────────────────
  // FK-safe: ServiceProvider (cascades ServiceProviderService) → Service
  // → BusinessUser → Business → User
  await prisma.serviceProvider.deleteMany({
    where: {
      businessId: { in: [E2E_SP_MUT_BIZ_ID, E2E_SP_MUT_OTHER_BIZ_ID] },
    },
  });
  await prisma.service.deleteMany({
    where: {
      id: {
        in: [
          E2E_SP_MUT_ACTIVE_SVC_ID,
          E2E_SP_MUT_INACTIVE_SVC_ID,
          E2E_SP_MUT_ORPHAN_SVC_ID,
          E2E_SP_MUT_OTHER_SVC_ID,
        ],
      },
    },
  });
  await prisma.businessUser.deleteMany({
    where: {
      businessId: { in: [E2E_SP_MUT_BIZ_ID, E2E_SP_MUT_OTHER_BIZ_ID] },
    },
  });
  await prisma.business.deleteMany({
    where: { id: { in: [E2E_SP_MUT_BIZ_ID, E2E_SP_MUT_OTHER_BIZ_ID] } },
  });
  await prisma.user.deleteMany({
    where: {
      id: {
        in: [
          E2E_SP_MUT_OWNER_USER_ID,
          E2E_SP_MUT_MGR_USER_ID,
          E2E_SP_MUT_MBR_USER_ID,
          E2E_SP_MUT_OUT_USER_ID,
          E2E_SP_MUT_SP_USER_ID,
          E2E_SP_MUT_INACT_SVC_SP_USER_ID,
          E2E_SP_MUT_BACKUP_SP_USER_ID,
          E2E_SP_MUT_ORPHAN_SP_USER_ID,
          E2E_SP_MUT_OTHER_USER_ID,
        ],
      },
    },
  });

  // ── Seed main business ─────────────────────────────────────────────────────
  await prisma.business.create({
    data: {
      id: E2E_SP_MUT_BIZ_ID,
      name: 'E2E SP Mutations Business',
      slug: 'e2e-sp-mutations-business',
      status: 'ACTIVE',
    },
  });

  ownerUser = await prisma.user.create({
    data: {
      id: E2E_SP_MUT_OWNER_USER_ID,
      phoneNormalized: '+19990009001',
      status: 'ACTIVE',
      platformRole: 'USER',
    },
  });
  const ownerBU = await prisma.businessUser.create({
    data: {
      businessId: E2E_SP_MUT_BIZ_ID,
      userId: ownerUser.id,
      role: 'OWNER',
      status: 'ACTIVE',
    },
  });
  ownerBUId = ownerBU.id;

  managerUser = await prisma.user.create({
    data: {
      id: E2E_SP_MUT_MGR_USER_ID,
      phoneNormalized: '+19990009002',
      status: 'ACTIVE',
      platformRole: 'USER',
    },
  });
  const managerBU = await prisma.businessUser.create({
    data: {
      businessId: E2E_SP_MUT_BIZ_ID,
      userId: managerUser.id,
      role: 'MANAGER',
      status: 'ACTIVE',
    },
  });
  managerBUId = managerBU.id;

  memberUser = await prisma.user.create({
    data: {
      id: E2E_SP_MUT_MBR_USER_ID,
      phoneNormalized: '+19990009003',
      status: 'ACTIVE',
      platformRole: 'USER',
    },
  });
  const memberBU = await prisma.businessUser.create({
    data: {
      businessId: E2E_SP_MUT_BIZ_ID,
      userId: memberUser.id,
      role: 'MEMBER',
      status: 'ACTIVE',
    },
  });
  memberBUId = memberBU.id;

  outsiderUser = await prisma.user.create({
    data: {
      id: E2E_SP_MUT_OUT_USER_ID,
      phoneNormalized: '+19990009004',
      status: 'ACTIVE',
      platformRole: 'USER',
    },
  });

  // Dedicated user/BU for the pre-seeded ServiceProvider
  const spUser = await prisma.user.create({
    data: {
      id: E2E_SP_MUT_SP_USER_ID,
      phoneNormalized: '+19990009005',
      status: 'ACTIVE',
      platformRole: 'USER',
    },
  });
  const spBU = await prisma.businessUser.create({
    data: {
      businessId: E2E_SP_MUT_BIZ_ID,
      userId: spUser.id,
      role: 'MEMBER',
      status: 'ACTIVE',
    },
  });
  spBUId = spBU.id;

  // Services
  await prisma.service.create({
    data: {
      id: E2E_SP_MUT_ACTIVE_SVC_ID,
      businessId: E2E_SP_MUT_BIZ_ID,
      name: 'Active Service',
      durationMinutes: 60,
      isActive: true,
      bufferBeforeMin: 0,
      bufferAfterMin: 0,
    },
  });
  await prisma.service.create({
    data: {
      id: E2E_SP_MUT_INACTIVE_SVC_ID,
      businessId: E2E_SP_MUT_BIZ_ID,
      name: 'Inactive Service',
      durationMinutes: 30,
      isActive: false,
      bufferBeforeMin: 0,
      bufferAfterMin: 0,
    },
  });

  // Pre-seeded ServiceProvider: linked to spBU + active service
  const existingSp = await prisma.serviceProvider.create({
    data: {
      businessId: E2E_SP_MUT_BIZ_ID,
      businessUserId: spBUId,
      displayName: 'Existing Provider',
      isActive: true,
      services: { create: [{ serviceId: E2E_SP_MUT_ACTIVE_SVC_ID }] },
    },
  });
  existingSpId = existingSp.id;

  // Inactive SP whose only assigned service is also inactive — activation-invariant tests
  const inactSvcSpUser = await prisma.user.create({
    data: {
      id: E2E_SP_MUT_INACT_SVC_SP_USER_ID,
      phoneNormalized: '+19990009006',
      status: 'ACTIVE',
      platformRole: 'USER',
    },
  });
  const inactSvcSpBU = await prisma.businessUser.create({
    data: {
      businessId: E2E_SP_MUT_BIZ_ID,
      userId: inactSvcSpUser.id,
      role: 'MEMBER',
      status: 'ACTIVE',
    },
  });
  await prisma.serviceProvider.create({
    data: {
      id: E2E_SP_MUT_INACT_SVC_SP_ID,
      businessId: E2E_SP_MUT_BIZ_ID,
      businessUserId: inactSvcSpBU.id,
      displayName: 'InactiveSvc Provider',
      isActive: false,
      services: { create: [{ serviceId: E2E_SP_MUT_INACTIVE_SVC_ID }] },
    },
  });

  // Backup active provider, also linked to E2E_SP_MUT_ACTIVE_SVC_ID, so the
  // RBAC tests on the status endpoint can toggle existingSpId freely without
  // ever leaving E2E_SP_MUT_ACTIVE_SVC_ID without an active provider.
  const backupSpUser = await prisma.user.create({
    data: {
      id: E2E_SP_MUT_BACKUP_SP_USER_ID,
      phoneNormalized: '+19990009007',
      status: 'ACTIVE',
      platformRole: 'USER',
    },
  });
  const backupSpBU = await prisma.businessUser.create({
    data: {
      businessId: E2E_SP_MUT_BIZ_ID,
      userId: backupSpUser.id,
      role: 'MEMBER',
      status: 'ACTIVE',
    },
  });
  await prisma.serviceProvider.create({
    data: {
      businessId: E2E_SP_MUT_BIZ_ID,
      businessUserId: backupSpBU.id,
      displayName: 'Backup Provider',
      isActive: true,
      services: { create: [{ serviceId: E2E_SP_MUT_ACTIVE_SVC_ID }] },
    },
  });

  // Dedicated active service + its sole active provider, isolated from the
  // rest of the suite — used only by the orphan-protection tests, which
  // deliberately trip the "last active provider" guard.
  await prisma.service.create({
    data: {
      id: E2E_SP_MUT_ORPHAN_SVC_ID,
      businessId: E2E_SP_MUT_BIZ_ID,
      name: 'Orphan-Guard Service',
      durationMinutes: 30,
      isActive: true,
      bufferBeforeMin: 0,
      bufferAfterMin: 0,
    },
  });
  const orphanSpUser = await prisma.user.create({
    data: {
      id: E2E_SP_MUT_ORPHAN_SP_USER_ID,
      phoneNormalized: '+19990009008',
      status: 'ACTIVE',
      platformRole: 'USER',
    },
  });
  const orphanSpBU = await prisma.businessUser.create({
    data: {
      businessId: E2E_SP_MUT_BIZ_ID,
      userId: orphanSpUser.id,
      role: 'MEMBER',
      status: 'ACTIVE',
    },
  });
  await prisma.serviceProvider.create({
    data: {
      id: E2E_SP_MUT_ORPHAN_SP_ID,
      businessId: E2E_SP_MUT_BIZ_ID,
      businessUserId: orphanSpBU.id,
      displayName: 'Orphan-Guard Provider',
      isActive: true,
      services: {
        create: [
          { serviceId: E2E_SP_MUT_ORPHAN_SVC_ID },
          { serviceId: E2E_SP_MUT_ACTIVE_SVC_ID },
        ],
      },
    },
  });

  // ── Cross-tenant fixture ───────────────────────────────────────────────────
  await prisma.business.create({
    data: {
      id: E2E_SP_MUT_OTHER_BIZ_ID,
      name: 'E2E SP Mutations Other Business',
      slug: 'e2e-sp-mutations-other-business',
      status: 'ACTIVE',
    },
  });
  const otherUser = await prisma.user.create({
    data: {
      id: E2E_SP_MUT_OTHER_USER_ID,
      phoneNormalized: '+19990009010',
      status: 'ACTIVE',
      platformRole: 'USER',
    },
  });
  const otherBU = await prisma.businessUser.create({
    data: {
      businessId: E2E_SP_MUT_OTHER_BIZ_ID,
      userId: otherUser.id,
      role: 'OWNER',
      status: 'ACTIVE',
    },
  });
  await prisma.service.create({
    data: {
      id: E2E_SP_MUT_OTHER_SVC_ID,
      businessId: E2E_SP_MUT_OTHER_BIZ_ID,
      name: 'Other Business Service',
      durationMinutes: 30,
      isActive: true,
      bufferBeforeMin: 0,
      bufferAfterMin: 0,
    },
  });
  const otherSp = await prisma.serviceProvider.create({
    data: {
      businessId: E2E_SP_MUT_OTHER_BIZ_ID,
      businessUserId: otherBU.id,
      displayName: 'Other Business Provider',
      isActive: true,
      services: { create: [{ serviceId: E2E_SP_MUT_OTHER_SVC_ID }] },
    },
  });
  otherSpId = otherSp.id;
});

afterAll(async () => {
  // Covers pre-seeded rows and any SPs created during tests
  await prisma.serviceProvider.deleteMany({
    where: {
      businessId: { in: [E2E_SP_MUT_BIZ_ID, E2E_SP_MUT_OTHER_BIZ_ID] },
    },
  });
  await prisma.service.deleteMany({
    where: {
      id: {
        in: [
          E2E_SP_MUT_ACTIVE_SVC_ID,
          E2E_SP_MUT_INACTIVE_SVC_ID,
          E2E_SP_MUT_ORPHAN_SVC_ID,
          E2E_SP_MUT_OTHER_SVC_ID,
        ],
      },
    },
  });
  await prisma.businessUser.deleteMany({
    where: {
      businessId: { in: [E2E_SP_MUT_BIZ_ID, E2E_SP_MUT_OTHER_BIZ_ID] },
    },
  });
  await prisma.business.deleteMany({
    where: { id: { in: [E2E_SP_MUT_BIZ_ID, E2E_SP_MUT_OTHER_BIZ_ID] } },
  });
  await prisma.user.deleteMany({
    where: {
      id: {
        in: [
          E2E_SP_MUT_OWNER_USER_ID,
          E2E_SP_MUT_MGR_USER_ID,
          E2E_SP_MUT_MBR_USER_ID,
          E2E_SP_MUT_OUT_USER_ID,
          E2E_SP_MUT_SP_USER_ID,
          E2E_SP_MUT_INACT_SVC_SP_USER_ID,
          E2E_SP_MUT_BACKUP_SP_USER_ID,
          E2E_SP_MUT_ORPHAN_SP_USER_ID,
          E2E_SP_MUT_OTHER_USER_ID,
        ],
      },
    },
  });
  await app.close();
});

beforeEach(() => {
  MockClerkAuthGuard.currentUser = null;
});

// ─── POST /dashboard/businesses/:businessId/service-providers ─────────────────

describe('POST /dashboard/businesses/:businessId/service-providers', () => {
  it('owner → 403 (creation restricted to platform administrators)', async () => {
    MockClerkAuthGuard.currentUser = ownerUser;
    await request(app.getHttpServer())
      .post(`/dashboard/businesses/${E2E_SP_MUT_BIZ_ID}/service-providers`)
      .send({
        displayName: 'Owner Provider',
        businessUserId: ownerBUId,
        serviceIds: [E2E_SP_MUT_ACTIVE_SVC_ID],
        isActive: true,
      })
      .expect(403);
  });

  it('manager → 403 (creation restricted to platform administrators)', async () => {
    MockClerkAuthGuard.currentUser = managerUser;
    await request(app.getHttpServer())
      .post(`/dashboard/businesses/${E2E_SP_MUT_BIZ_ID}/service-providers`)
      .send({
        displayName: 'Manager Provider',
        businessUserId: managerBUId,
        serviceIds: [E2E_SP_MUT_ACTIVE_SVC_ID],
      })
      .expect(403);
  });

  it('member → 403', async () => {
    MockClerkAuthGuard.currentUser = memberUser;
    await request(app.getHttpServer())
      .post(`/dashboard/businesses/${E2E_SP_MUT_BIZ_ID}/service-providers`)
      .send({
        displayName: 'Member Provider',
        businessUserId: spBUId,
        serviceIds: [E2E_SP_MUT_ACTIVE_SVC_ID],
      })
      .expect(403);
  });

  it('outsider → 403', async () => {
    MockClerkAuthGuard.currentUser = outsiderUser;
    await request(app.getHttpServer())
      .post(`/dashboard/businesses/${E2E_SP_MUT_BIZ_ID}/service-providers`)
      .send({
        displayName: 'Outsider Provider',
        businessUserId: ownerBUId,
        serviceIds: [E2E_SP_MUT_ACTIVE_SVC_ID],
      })
      .expect(403);
  });

  it('missing auth → 401', async () => {
    await request(app.getHttpServer())
      .post(`/dashboard/businesses/${E2E_SP_MUT_BIZ_ID}/service-providers`)
      .send({
        displayName: 'Anon Provider',
        businessUserId: ownerBUId,
        serviceIds: [E2E_SP_MUT_ACTIVE_SVC_ID],
      })
      .expect(401);
  });

  it('non-existent businessId → 403', async () => {
    MockClerkAuthGuard.currentUser = ownerUser;
    await request(app.getHttpServer())
      .post(
        '/dashboard/businesses/00000000-0000-4000-8000-000000000000/service-providers',
      )
      .send({
        displayName: 'Provider',
        businessUserId: ownerBUId,
        serviceIds: [E2E_SP_MUT_ACTIVE_SVC_ID],
      })
      .expect(403);
  });

  it('owner of another tenant calls other businessId → 403', async () => {
    // ownerUser belongs to E2E_SP_MUT_BIZ_ID, not E2E_SP_MUT_OTHER_BIZ_ID
    MockClerkAuthGuard.currentUser = ownerUser;
    await request(app.getHttpServer())
      .post(
        `/dashboard/businesses/${E2E_SP_MUT_OTHER_BIZ_ID}/service-providers`,
      )
      .send({
        displayName: 'Provider',
        businessUserId: ownerBUId,
        serviceIds: [E2E_SP_MUT_ACTIVE_SVC_ID],
      })
      .expect(403);
  });

  it('missing displayName → 403 (handler blocks before validation)', async () => {
    MockClerkAuthGuard.currentUser = ownerUser;
    await request(app.getHttpServer())
      .post(`/dashboard/businesses/${E2E_SP_MUT_BIZ_ID}/service-providers`)
      .send({
        businessUserId: ownerBUId,
        serviceIds: [E2E_SP_MUT_ACTIVE_SVC_ID],
      })
      .expect(403);
  });

  it('empty displayName → 403 (handler blocks before validation)', async () => {
    MockClerkAuthGuard.currentUser = ownerUser;
    await request(app.getHttpServer())
      .post(`/dashboard/businesses/${E2E_SP_MUT_BIZ_ID}/service-providers`)
      .send({
        displayName: '',
        businessUserId: ownerBUId,
        serviceIds: [E2E_SP_MUT_ACTIVE_SVC_ID],
      })
      .expect(403);
  });

  it('missing serviceIds → 403 (handler blocks before validation)', async () => {
    MockClerkAuthGuard.currentUser = ownerUser;
    await request(app.getHttpServer())
      .post(`/dashboard/businesses/${E2E_SP_MUT_BIZ_ID}/service-providers`)
      .send({ displayName: 'Provider', businessUserId: ownerBUId })
      .expect(403);
  });

  it('empty serviceIds array → 403 (handler blocks before validation)', async () => {
    MockClerkAuthGuard.currentUser = ownerUser;
    await request(app.getHttpServer())
      .post(`/dashboard/businesses/${E2E_SP_MUT_BIZ_ID}/service-providers`)
      .send({
        displayName: 'Provider',
        businessUserId: ownerBUId,
        serviceIds: [],
      })
      .expect(403);
  });

  it('missing businessUserId → 403 (handler blocks before validation)', async () => {
    MockClerkAuthGuard.currentUser = ownerUser;
    await request(app.getHttpServer())
      .post(`/dashboard/businesses/${E2E_SP_MUT_BIZ_ID}/service-providers`)
      .send({ displayName: 'Provider', serviceIds: [E2E_SP_MUT_ACTIVE_SVC_ID] })
      .expect(403);
  });

  it('businessUserId not in this business → 403 (handler blocks before service call)', async () => {
    MockClerkAuthGuard.currentUser = ownerUser;
    await request(app.getHttpServer())
      .post(`/dashboard/businesses/${E2E_SP_MUT_BIZ_ID}/service-providers`)
      .send({
        displayName: 'Provider',
        businessUserId: '00000000-0000-4000-8000-000000000099',
        serviceIds: [E2E_SP_MUT_ACTIVE_SVC_ID],
      })
      .expect(403);
  });

  it('duplicate businessUserId → 403 (handler blocks before service call)', async () => {
    MockClerkAuthGuard.currentUser = ownerUser;
    await request(app.getHttpServer())
      .post(`/dashboard/businesses/${E2E_SP_MUT_BIZ_ID}/service-providers`)
      .send({
        displayName: 'Duplicate Provider',
        businessUserId: ownerBUId,
        serviceIds: [E2E_SP_MUT_ACTIVE_SVC_ID],
      })
      .expect(403);
  });

  it('cross-tenant serviceId → 403 (handler blocks before service call)', async () => {
    MockClerkAuthGuard.currentUser = ownerUser;
    await request(app.getHttpServer())
      .post(`/dashboard/businesses/${E2E_SP_MUT_BIZ_ID}/service-providers`)
      .send({
        displayName: 'Provider',
        businessUserId: memberBUId,
        serviceIds: [E2E_SP_MUT_OTHER_SVC_ID],
      })
      .expect(403);
  });

  it('linking inactive service to active ServiceProvider → 403 (handler blocks before service call)', async () => {
    MockClerkAuthGuard.currentUser = ownerUser;
    await request(app.getHttpServer())
      .post(`/dashboard/businesses/${E2E_SP_MUT_BIZ_ID}/service-providers`)
      .send({
        displayName: 'Provider',
        businessUserId: memberBUId,
        serviceIds: [E2E_SP_MUT_INACTIVE_SVC_ID],
        isActive: true,
      })
      .expect(403);
  });
});

// ─── PATCH /dashboard/businesses/:businessId/service-providers/:id ────────────

describe('PATCH /dashboard/businesses/:businessId/service-providers/:serviceProviderId', () => {
  it('owner → 200 with updated displayName', async () => {
    MockClerkAuthGuard.currentUser = ownerUser;
    const res = await request(app.getHttpServer())
      .patch(
        `/dashboard/businesses/${E2E_SP_MUT_BIZ_ID}/service-providers/${existingSpId}`,
      )
      .send({ displayName: 'Updated By Owner' })
      .expect(200);

    const body = res.body as ServiceProviderDto;
    expect(body.id).toBe(existingSpId);
    expect(body.displayName).toBe('Updated By Owner');
    expect(body.businessUserId).toBe(spBUId);
    expect(body.serviceIds).toContain(E2E_SP_MUT_ACTIVE_SVC_ID);
  });

  it('manager → 200 with updated displayName', async () => {
    MockClerkAuthGuard.currentUser = managerUser;
    const res = await request(app.getHttpServer())
      .patch(
        `/dashboard/businesses/${E2E_SP_MUT_BIZ_ID}/service-providers/${existingSpId}`,
      )
      .send({ displayName: 'Updated By Manager' })
      .expect(200);

    expect((res.body as ServiceProviderDto).displayName).toBe(
      'Updated By Manager',
    );
  });

  it('member → 403', async () => {
    MockClerkAuthGuard.currentUser = memberUser;
    await request(app.getHttpServer())
      .patch(
        `/dashboard/businesses/${E2E_SP_MUT_BIZ_ID}/service-providers/${existingSpId}`,
      )
      .send({ displayName: 'Member Attempt' })
      .expect(403);
  });

  it('outsider → 403', async () => {
    MockClerkAuthGuard.currentUser = outsiderUser;
    await request(app.getHttpServer())
      .patch(
        `/dashboard/businesses/${E2E_SP_MUT_BIZ_ID}/service-providers/${existingSpId}`,
      )
      .send({ displayName: 'Outsider Attempt' })
      .expect(403);
  });

  it('missing auth → 401', async () => {
    await request(app.getHttpServer())
      .patch(
        `/dashboard/businesses/${E2E_SP_MUT_BIZ_ID}/service-providers/${existingSpId}`,
      )
      .send({ displayName: 'Anon Attempt' })
      .expect(401);
  });

  it('non-existent businessId → 403', async () => {
    MockClerkAuthGuard.currentUser = ownerUser;
    await request(app.getHttpServer())
      .patch(
        `/dashboard/businesses/00000000-0000-4000-8000-000000000000/service-providers/${existingSpId}`,
      )
      .send({ displayName: 'Update' })
      .expect(403);
  });

  it('owner of another tenant calls other businessId → 403', async () => {
    MockClerkAuthGuard.currentUser = ownerUser;
    await request(app.getHttpServer())
      .patch(
        `/dashboard/businesses/${E2E_SP_MUT_OTHER_BIZ_ID}/service-providers/${otherSpId}`,
      )
      .send({ displayName: 'Update' })
      .expect(403);
  });

  it('non-existent serviceProviderId → 404', async () => {
    MockClerkAuthGuard.currentUser = ownerUser;
    await request(app.getHttpServer())
      .patch(
        `/dashboard/businesses/${E2E_SP_MUT_BIZ_ID}/service-providers/00000000-0000-4000-8000-000000000099`,
      )
      .send({ displayName: 'Update' })
      .expect(404);
  });

  it('cross-tenant serviceProviderId → 404', async () => {
    // The other business's SP ID passed to the main business endpoint
    MockClerkAuthGuard.currentUser = ownerUser;
    await request(app.getHttpServer())
      .patch(
        `/dashboard/businesses/${E2E_SP_MUT_BIZ_ID}/service-providers/${otherSpId}`,
      )
      .send({ displayName: 'Cross Tenant' })
      .expect(404);
  });

  it('empty displayName → 400', async () => {
    MockClerkAuthGuard.currentUser = ownerUser;
    await request(app.getHttpServer())
      .patch(
        `/dashboard/businesses/${E2E_SP_MUT_BIZ_ID}/service-providers/${existingSpId}`,
      )
      .send({ displayName: '' })
      .expect(400);
  });

  it('empty serviceIds array → 400', async () => {
    MockClerkAuthGuard.currentUser = ownerUser;
    await request(app.getHttpServer())
      .patch(
        `/dashboard/businesses/${E2E_SP_MUT_BIZ_ID}/service-providers/${existingSpId}`,
      )
      .send({ serviceIds: [] })
      .expect(400);
  });

  it('cross-tenant serviceId in serviceIds → 400', async () => {
    MockClerkAuthGuard.currentUser = ownerUser;
    await request(app.getHttpServer())
      .patch(
        `/dashboard/businesses/${E2E_SP_MUT_BIZ_ID}/service-providers/${existingSpId}`,
      )
      .send({ serviceIds: [E2E_SP_MUT_OTHER_SVC_ID] })
      .expect(400);
  });

  it('isActive: true with no serviceIds when existing services are all inactive → 200 (assignment is configuration, independent of activation)', async () => {
    MockClerkAuthGuard.currentUser = ownerUser;
    const res = await request(app.getHttpServer())
      .patch(
        `/dashboard/businesses/${E2E_SP_MUT_BIZ_ID}/service-providers/${E2E_SP_MUT_INACT_SVC_SP_ID}`,
      )
      .send({ isActive: true })
      .expect(200);

    const body = res.body as ServiceProviderDto;
    expect(body.isActive).toBe(true);
    expect(body.serviceIds).toContain(E2E_SP_MUT_INACTIVE_SVC_ID);
  });
});

// ─── PATCH /dashboard/businesses/:businessId/service-providers/:id/status ─────

describe('PATCH /dashboard/businesses/:businessId/service-providers/:serviceProviderId/status', () => {
  it('owner → 200 sets isActive false', async () => {
    MockClerkAuthGuard.currentUser = ownerUser;
    const res = await request(app.getHttpServer())
      .patch(
        `/dashboard/businesses/${E2E_SP_MUT_BIZ_ID}/service-providers/${existingSpId}/status`,
      )
      .send({ isActive: false })
      .expect(200);

    const body = res.body as ServiceProviderDto;
    expect(body.id).toBe(existingSpId);
    expect(body.isActive).toBe(false);
  });

  it('manager → 200 sets isActive true', async () => {
    // Restore isActive after the owner test set it to false
    MockClerkAuthGuard.currentUser = managerUser;
    const res = await request(app.getHttpServer())
      .patch(
        `/dashboard/businesses/${E2E_SP_MUT_BIZ_ID}/service-providers/${existingSpId}/status`,
      )
      .send({ isActive: true })
      .expect(200);

    expect((res.body as ServiceProviderDto).isActive).toBe(true);
  });

  it('member → 403', async () => {
    MockClerkAuthGuard.currentUser = memberUser;
    await request(app.getHttpServer())
      .patch(
        `/dashboard/businesses/${E2E_SP_MUT_BIZ_ID}/service-providers/${existingSpId}/status`,
      )
      .send({ isActive: false })
      .expect(403);
  });

  it('outsider → 403', async () => {
    MockClerkAuthGuard.currentUser = outsiderUser;
    await request(app.getHttpServer())
      .patch(
        `/dashboard/businesses/${E2E_SP_MUT_BIZ_ID}/service-providers/${existingSpId}/status`,
      )
      .send({ isActive: false })
      .expect(403);
  });

  it('missing auth → 401', async () => {
    await request(app.getHttpServer())
      .patch(
        `/dashboard/businesses/${E2E_SP_MUT_BIZ_ID}/service-providers/${existingSpId}/status`,
      )
      .send({ isActive: false })
      .expect(401);
  });

  it('non-existent businessId → 403', async () => {
    MockClerkAuthGuard.currentUser = ownerUser;
    await request(app.getHttpServer())
      .patch(
        `/dashboard/businesses/00000000-0000-4000-8000-000000000000/service-providers/${existingSpId}/status`,
      )
      .send({ isActive: false })
      .expect(403);
  });

  it('owner of another tenant calls other businessId → 403', async () => {
    MockClerkAuthGuard.currentUser = ownerUser;
    await request(app.getHttpServer())
      .patch(
        `/dashboard/businesses/${E2E_SP_MUT_OTHER_BIZ_ID}/service-providers/${otherSpId}/status`,
      )
      .send({ isActive: false })
      .expect(403);
  });

  it('non-existent serviceProviderId → 404', async () => {
    MockClerkAuthGuard.currentUser = ownerUser;
    await request(app.getHttpServer())
      .patch(
        `/dashboard/businesses/${E2E_SP_MUT_BIZ_ID}/service-providers/00000000-0000-4000-8000-000000000099/status`,
      )
      .send({ isActive: false })
      .expect(404);
  });

  it('cross-tenant serviceProviderId → 404', async () => {
    MockClerkAuthGuard.currentUser = ownerUser;
    await request(app.getHttpServer())
      .patch(
        `/dashboard/businesses/${E2E_SP_MUT_BIZ_ID}/service-providers/${otherSpId}/status`,
      )
      .send({ isActive: false })
      .expect(404);
  });

  it('missing isActive → 400', async () => {
    MockClerkAuthGuard.currentUser = ownerUser;
    await request(app.getHttpServer())
      .patch(
        `/dashboard/businesses/${E2E_SP_MUT_BIZ_ID}/service-providers/${existingSpId}/status`,
      )
      .send({})
      .expect(400);
  });

  it('activating when all assigned services are inactive → 200 (assignment is configuration, independent of activation)', async () => {
    MockClerkAuthGuard.currentUser = ownerUser;
    const res = await request(app.getHttpServer())
      .patch(
        `/dashboard/businesses/${E2E_SP_MUT_BIZ_ID}/service-providers/${E2E_SP_MUT_INACT_SVC_SP_ID}/status`,
      )
      .send({ isActive: true })
      .expect(200);

    expect((res.body as ServiceProviderDto).isActive).toBe(true);
  });
});

// ─── Service ↔ ServiceProvider activation policy ───────────────────────────────
// Assignment is configuration, independent of either side's activation
// state. A Service may only activate while it has at least one active
// ServiceProvider; removing/deactivating the last such provider is rejected.

describe('Service ↔ ServiceProvider activation policy', () => {
  it('assigning an inactive service to an already-active ServiceProvider → 200', async () => {
    MockClerkAuthGuard.currentUser = ownerUser;
    const res = await request(app.getHttpServer())
      .patch(
        `/dashboard/businesses/${E2E_SP_MUT_BIZ_ID}/service-providers/${existingSpId}`,
      )
      .send({
        serviceIds: [E2E_SP_MUT_ACTIVE_SVC_ID, E2E_SP_MUT_INACTIVE_SVC_ID],
      })
      .expect(200);

    const body = res.body as ServiceProviderDto;
    expect(body.isActive).toBe(true);
    expect(body.serviceIds).toEqual(
      expect.arrayContaining([
        E2E_SP_MUT_ACTIVE_SVC_ID,
        E2E_SP_MUT_INACTIVE_SVC_ID,
      ]),
    );
  });

  it('removing the last active-provider assignment from an active service → 400', async () => {
    // E2E_SP_MUT_ORPHAN_SP_ID is the sole active provider of
    // E2E_SP_MUT_ORPHAN_SVC_ID. Dropping that link would leave the service
    // with zero active providers.
    MockClerkAuthGuard.currentUser = ownerUser;
    await request(app.getHttpServer())
      .patch(
        `/dashboard/businesses/${E2E_SP_MUT_BIZ_ID}/service-providers/${E2E_SP_MUT_ORPHAN_SP_ID}`,
      )
      .send({ serviceIds: [E2E_SP_MUT_ACTIVE_SVC_ID] })
      .expect(400);
  });

  it('removing a service link that still has another active provider → 200', async () => {
    // E2E_SP_MUT_ACTIVE_SVC_ID also has existingSpId/backup providers, so
    // dropping it from the orphan-guard provider does not orphan it.
    MockClerkAuthGuard.currentUser = ownerUser;
    const res = await request(app.getHttpServer())
      .patch(
        `/dashboard/businesses/${E2E_SP_MUT_BIZ_ID}/service-providers/${E2E_SP_MUT_ORPHAN_SP_ID}`,
      )
      .send({ serviceIds: [E2E_SP_MUT_ORPHAN_SVC_ID] })
      .expect(200);

    expect((res.body as ServiceProviderDto).serviceIds).toEqual([
      E2E_SP_MUT_ORPHAN_SVC_ID,
    ]);
  });

  it('deactivating the only active provider of an active service → 400', async () => {
    // After the previous test, E2E_SP_MUT_ORPHAN_SP_ID is linked solely to
    // E2E_SP_MUT_ORPHAN_SVC_ID, and is still its only active provider.
    MockClerkAuthGuard.currentUser = ownerUser;
    await request(app.getHttpServer())
      .patch(
        `/dashboard/businesses/${E2E_SP_MUT_BIZ_ID}/service-providers/${E2E_SP_MUT_ORPHAN_SP_ID}/status`,
      )
      .send({ isActive: false })
      .expect(400);
  });

  it('service activation succeeds when at least one active provider is assigned', async () => {
    MockClerkAuthGuard.currentUser = ownerUser;
    await request(app.getHttpServer())
      .patch(
        `/dashboard/businesses/${E2E_SP_MUT_BIZ_ID}/services/${E2E_SP_MUT_ACTIVE_SVC_ID}/status`,
      )
      .send({ isActive: false })
      .expect(200);

    const res = await request(app.getHttpServer())
      .patch(
        `/dashboard/businesses/${E2E_SP_MUT_BIZ_ID}/services/${E2E_SP_MUT_ACTIVE_SVC_ID}/status`,
      )
      .send({ isActive: true })
      .expect(200);

    expect((res.body as { isActive: boolean }).isActive).toBe(true);
  });
});
